/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Items;


import Model.HoaDon;
import Utility.UtilityDate;
import java.awt.Color;

/**
 *
 * @author ADMIN
 */
public class ItemHoaDon extends javax.swing.JPanel {
    private HoaDon hd=null;
    int index;
    /**
     * Creates new form ItemXemay
     */
    public ItemHoaDon(HoaDon x,int i) {
        initComponents();
        hd=x;
        index=i;
        lblMaHoaDon.setText(hd.getMaHoaDon());
        lblMaKhachHang.setText(hd.getMaKhachHang());
        lblMaNV.setText(hd.getMaNhanVien());
        lblTongtien.setText(Utility.UtilityFormat.DinhdangVnd(x.getTongTien()));
        lblNgayTao.setText(UtilityDate.DateToString(hd.getNgayTao()));
    }
    public void Choose(){
        pnlItem.setBackground(new Color(175, 175, 220));
        
        lblMaHoaDon.setForeground(Color.white);
        lblMaKhachHang.setForeground(Color.white);
        lblMaNV.setForeground(Color.white);
        lblTongtien.setForeground(Color.white);
        lblNgayTao.setForeground(Color.white);
        
        lblLabel1.setForeground(Color.white);
        lblLabel2.setForeground(Color.white);
        lblLabel3.setForeground(Color.white);
        lblLabel4.setForeground(Color.white);
        lblLabel5.setForeground(Color.white);
    }
    public void RemoveChoose(){
        pnlItem.setBackground(Color.WHITE);
        
        lblNgayTao.setForeground(Color.black);
        lblMaHoaDon.setForeground(Color.black);
        lblMaKhachHang.setForeground(Color.black);
        lblMaNV.setForeground(Color.black);
        lblTongtien.setForeground(Color.black);
        
        lblLabel1.setForeground(Color.black);
        lblLabel2.setForeground(Color.black);
        lblLabel3.setForeground(Color.black);
        lblLabel4.setForeground(Color.black);
        lblLabel5.setForeground(Color.black);

    }
    public String RutGonChuoi(String x){
        String chuoi=x;
        if(chuoi.length()>19){//chi rut gon nhung chuoi co do dai tren 19 ky tu
            StringBuilder sb = new StringBuilder(22);//tao do dai toi da cho chuoi la 22;
            for (int i = 0; i < 22; i++) {          
                if(i>18){
                    sb.append('.');// 3 ky tu cuoi cung là ... 
                }else{                   
                    sb.append(chuoi.charAt(i));     //nhung ky tu con lai add vao Stringbuilder               
                }
            }
            chuoi=sb.toString();//chuyen sang String;
        }
        return chuoi;
    }
    public int getIndex() {
        return index;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlItem = new javax.swing.JPanel();
        lblLabel1 = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();
        lblLabel2 = new javax.swing.JLabel();
        lblMaKhachHang = new javax.swing.JLabel();
        lblLabel3 = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblLabel4 = new javax.swing.JLabel();
        lblTongtien = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        lblLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlItem.setBackground(new java.awt.Color(255, 255, 255));

        lblLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLabel1.setText("Mã hóa đơn :");

        lblMaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaHoaDon.setText("jLabel4");

        lblLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLabel2.setText("Mã khách hàng :");

        lblMaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaKhachHang.setText("jLabel4");

        lblLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLabel3.setText("Mã nhân viên :");

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaNV.setText("jLabel4");

        lblLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLabel4.setText("Tổng tiền");

        lblTongtien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTongtien.setText("jLabel4");

        lblNgayTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNgayTao.setText("jLabel4");

        lblLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLabel5.setText("Ngày tạo");

        javax.swing.GroupLayout pnlItemLayout = new javax.swing.GroupLayout(pnlItem);
        pnlItem.setLayout(pnlItemLayout);
        pnlItemLayout.setHorizontalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        pnlItemLayout.setVerticalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabel1)
                    .addComponent(lblMaHoaDon))
                .addGap(18, 18, 18)
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabel2)
                    .addComponent(lblMaKhachHang))
                .addGap(21, 21, 21)
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabel3)
                    .addComponent(lblMaNV))
                .addGap(18, 18, 18)
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabel4)
                    .addComponent(lblTongtien))
                .addGap(18, 18, 18)
                .addGroup(pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabel5)
                    .addComponent(lblNgayTao))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLabel1;
    private javax.swing.JLabel lblLabel2;
    private javax.swing.JLabel lblLabel3;
    private javax.swing.JLabel lblLabel4;
    private javax.swing.JLabel lblLabel5;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaKhachHang;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblTongtien;
    private javax.swing.JPanel pnlItem;
    // End of variables declaration//GEN-END:variables
}
