/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GioHang;

import DAO.HoaDonChiTietDAO;
import DAO.HoaDonDAO;
import Model.HoaDon;
import Model.HoaDonChiTiet;
import Model.User;
import Utility.UtilityFormat;
import View.QuanLyGiohang;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class itemGioHang extends javax.swing.JPanel {

    QuanLyGiohang main;
    GioHang giohang;

    /**
     * Creates new form pnlGioHang
     */
    public itemGioHang(GioHang gh, QuanLyGiohang main) {
        initComponents();
        this.main = main;
        this.giohang = gh;
        loadGioHang(gh);

    }

    public void loadGioHang(GioHang gh) {
        txtMaKhachHang.setText(gh.getMaKhachHang());
        txaSanPham.setText("");
        for (SanPham sp : gh.getListSanPham()) {
            String Masanpham = sp.getMaSanPham();
            String Tensanpham = sp.getTenSanPham();
            int Soluong = sp.getSoluong();
            String giatien = UtilityFormat.DinhdangVnd(sp.getGiatien());
            txaSanPham.append("Tên sản phẩm : " + Tensanpham + "\n"
                    + "Mã sản phẩm : " + Masanpham + "\n"
                    + "Số lượng : " + Soluong + "\n"
                    + "Giá tiền/1 Sản phẩm: " + giatien + "\n\n"
            );
        }
        txtTongTien.setText(UtilityFormat.DinhdangVnd(gh.tongtien()));
    }

    public boolean CreateHoaDon(String MaHoaDon) {
        if (MaHoaDon != null && !MaHoaDon.isBlank()) {
            HoaDon hd = new HoaDon();
            hd.setMaHoaDon(MaHoaDon);
            hd.setMaKhachHang(giohang.getMaKhachHang());
            hd.setMaNhanVien(User.getUser().getMaNhanVien());

            int Error = new HoaDonDAO().Them(hd);
            switch (Error) {
                case 2627 -> {
                    JOptionPane.showMessageDialog(txtTongTien, "Mã đơn hàng đã tồn tại");
                    return false;
                }
                case 51000 -> {
                    JOptionPane.showMessageDialog(txtTongTien, "Mã khách hàng không tồn tại");
                    return false;
                }
                default -> {
                    return true;
                }
            }
        } else {
            return false;
        }
    }

    public boolean CreateHoaDonChiTiet(String MaHoaDon) {
        int Error = 0;
        for (SanPham sp : giohang.getListSanPham()) {
            HoaDonChiTiet hdct = new HoaDonChiTiet();
            hdct.setMaHoaDon(MaHoaDon);
            hdct.setLoaiSanpham(sp.getLoaiSanPham());
            hdct.setMaSanPham(sp.getMaSanPham());
            hdct.setSoluong(sp.getSoluong());
            hdct.setGiaTien(sp.getGiatien());
            Error = new HoaDonChiTietDAO().Them(hdct);
            switch (Error) {
                case 51000 -> {
                    JOptionPane.showMessageDialog(txtTongTien, "Mã xe không tồn tại");
                    return false;
                }
                case 51001 -> {
                    JOptionPane.showMessageDialog(txtTongTien, "Mã phụ kiện không tồn tại");
                    return false;
                }
                case 51002 -> {
                    JOptionPane.showMessageDialog(txtTongTien, "Số lượng không hợp lý");
                    return false;
                }
                case 52000 -> {
                    JOptionPane.showMessageDialog(txtTongTien, "Mã sản phẩm không hợp lệ");
                    return false;
                }
                default -> {

                }
            }
        }
        return true;
    }

    public String autoId() {
        int nextId = new HoaDonDAO().getLastId() + 1;
        return "HD" + nextId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSanPham = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        btnXoagiohang = new javax.swing.JButton();
        btnThanhtoan = new javax.swing.JButton();
        btnXoasanpham = new javax.swing.JButton();

        setBackground(new java.awt.Color(175, 175, 220));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mã khách hàng :");

        txtMaKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtMaKhachHang.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Sản phẩm :");

        txaSanPham.setColumns(20);
        txaSanPham.setRows(5);
        txaSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txaSanPham.setFocusable(false);
        jScrollPane1.setViewportView(txaSanPham);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tổng tiền :");

        txtTongTien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtTongTien.setFocusable(false);

        btnXoagiohang.setText("Xóa giỏ hàng");
        btnXoagiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoagiohangActionPerformed(evt);
            }
        });

        btnThanhtoan.setText("Thanh toán");
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        btnXoasanpham.setText("Xóa sản phẩm");
        btnXoasanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoasanphamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaKhachHang))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongTien))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnXoagiohang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoasanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoagiohang)
                    .addComponent(btnThanhtoan)
                    .addComponent(btnXoasanpham))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoagiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoagiohangActionPerformed
        if (Utility.UtilityNotificate.confirmDialog("Xác nhận xóa giỏ hàng của khách : "+giohang.getMaKhachHang()) == 1)
        ControllerGioHang.XoaGioHang(txtMaKhachHang.getText());
        main.LoadTable();
    }//GEN-LAST:event_btnXoagiohangActionPerformed

    private void btnXoasanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoasanphamActionPerformed
        String mangsanpham = JOptionPane.showInputDialog("Nhập mã sản phẩm ");
        if (mangsanpham != null && !mangsanpham.isBlank()) {
            boolean check = ControllerGioHang.XoaNhieuSanPhamChoKhach(txtMaKhachHang.getText(), mangsanpham);
            if (check) {
                main.LoadTable();
                JOptionPane.showMessageDialog(txtTongTien, "Xóa sản phẩm thành công");
            } else {
                JOptionPane.showMessageDialog(txtTongTien, "Mã sản phẩm không đúng");
            }
        }
    }//GEN-LAST:event_btnXoasanphamActionPerformed

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        if (!giohang.getListSanPham().isEmpty()) {
            if (Utility.UtilityNotificate.confirmDialog("Xác nhận thanh toán") == 1) {
                String MaHoaDon = autoId();
                boolean result = false;
                if (MaHoaDon != null && !MaHoaDon.isBlank()) {
                    result = CreateHoaDon(MaHoaDon);
                    if (result) {
                        result = CreateHoaDonChiTiet(MaHoaDon);
                        if (!result) {
                            JOptionPane.showMessageDialog(txtTongTien, "Thanh toán thất bại");
                        } else {
                            ControllerGioHang.XoaGioHang(giohang.getMaKhachHang());
                            main.LoadTable();
                            JOptionPane.showMessageDialog(txtTongTien, "Thanh toán thành công");
                        }
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(txtTongTien, "Giỏ hàng rỗng");
        }
    }//GEN-LAST:event_btnThanhtoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JButton btnXoagiohang;
    private javax.swing.JButton btnXoasanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaSanPham;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
