/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ViewThongke;

import DAO.ThongKeDAO;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.Label;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ADMIN
 */
public class ThongkeKhachmoi extends javax.swing.JPanel {

    ThongKeDAO DAO = new ThongKeDAO();

    /**
     * Creates new form ThongkeTongthu
     */
    public ThongkeKhachmoi() {
        initComponents();
        setYearCbo();

    }

    private void setYearCbo() {
        Calendar calendar = Calendar.getInstance();
        int currentYear = calendar.get(Calendar.YEAR);//lấy năm
        for (int i = 0; i < 10; i++) {
            cboYear.addItem(String.valueOf(currentYear));
            currentYear -= 1; //lay nam hien tai và 10 nam truoc            
        }
    }

    private void loadThongKeKhachMoi() {
        DefaultTableModel model = (DefaultTableModel) tblThongke.getModel();
        model.setRowCount(0);
        String chuoi = (String) cboYear.getSelectedItem();
        int Nam = Integer.parseInt(chuoi);
        List<Object[]> list = DAO.getThongKeKhachmoi(Nam);
        for (Object[] objects : list) {
            model.addRow(objects);
        }
    }

    private void exportToExcel(String path) {
        try {
            // Tạo một tệp Excel mới
            WritableWorkbook workbook = Workbook.createWorkbook(new File(path + "\\ThongKeKhachMoi.xls"));
            WritableSheet sheet = workbook.createSheet("ThongKeKhachMoi", 0);

            // Ghi tên các cột vào tệp Excel
            for (int i = 0; i < tblThongke.getColumnCount(); i++) {
                Label label = new Label(i, 0, tblThongke.getColumnName(i));
                sheet.addCell(label);
            }

            // Ghi dữ liệu từ bảng vào tệp Excel
            for (int i = 0; i < tblThongke.getRowCount(); i++) {
                for (int j = 0; j < tblThongke.getColumnCount(); j++) {
                    Object cellValue = tblThongke.getValueAt(i, j);
                    Label label = new Label(j, i + 1, cellValue.toString());
                    sheet.addCell(label);
                }
            }

            // Lưu tệp Excel
            workbook.write();
            workbook.close();

            JOptionPane.showMessageDialog(this, "Xuất file Excel thành công!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tạo hoặc ghi file Excel: " + ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
    }

    private void createBarChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Lấy dữ liệu từ bảng và thêm vào dataset
        for (int i = 0; i < tblThongke.getRowCount(); i++) {
            String label = tblThongke.getValueAt(i, 0).toString(); // Nhãn tháng
            int soLuong = Integer.parseInt(tblThongke.getValueAt(i, 1).toString()); // Số lượng khách mới

            dataset.addValue(soLuong, "Số lượng khách mới", label);
        }

        JFreeChart barChart = ChartFactory.createBarChart(
                "Biểu đồ số lượng khách mới theo tháng", // Tiêu đề biểu đồ
                "Tháng", // Nhãn trục x
                "Số lượng khách mới", // Nhãn trục y
                dataset, // Dataset
                PlotOrientation.VERTICAL,
                true, true, false);

        // Tạo và hiển thị biểu đồ
        ChartPanel chartPanel = new ChartPanel(barChart);
        JFrame frame = new JFrame("Biểu đồ cột");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(chartPanel);
        frame.pack();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboYear = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongke = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 228, 228));

        jLabel1.setText("Năm");

        cboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboYearActionPerformed(evt);
            }
        });

        tblThongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tháng ", "Số lượng khách mới"
            }
        ));
        jScrollPane1.setViewportView(tblThongke);

        jButton1.setText("Biểu đồ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboYearActionPerformed
        loadThongKeKhachMoi();
    }//GEN-LAST:event_cboYearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        createBarChart();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String pathSave = Utility.UtilityImage.chooseFilePath();
        if (pathSave != null) {
            exportToExcel(pathSave);
        }

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboYear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblThongke;
    // End of variables declaration//GEN-END:variables
}
