/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab6;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.awt.Color;

/**
 *
 * @author Tinh
 */
public class Color2 extends javax.swing.JFrame {

    /**
     * Creates new form Color
     */
    ArrayList<Color> list = new ArrayList<>();
    @SuppressWarnings("empty-statement")
    public Color2() {
        initComponents();
        this.setLocationRelativeTo(null);
        list.add(Color.BLACK);
        list.add(Color.BLUE);
        list.add(Color.GRAY);
        list.add(Color.RED);
        list.add(Color.CYAN);
        list.add(Color.YELLOW);
        list.add(Color.ORANGE);
//        list.add(new Color1(255, 255, 255));
//        list.add(new Color1(255, 0, 0));
//        list.add(new Color1(0, 255, 0));
//        list.add(new Color1(255, 255, 0));
//        list.add(new Color1(128, 0, 128));
//        list.add(new Color1(255, 0, 255));
//        list.add(new Color1(0, 0, 0));
//        list.add(new Color1(43, 43, 2));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJava = new javax.swing.JLabel();
        btnJava = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtJava.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtJava.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJava.setText("JAVA");

        btnJava.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJava.setText("Đổi màu");
        btnJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJavaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(txtJava, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnJava, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtJava, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJava, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJavaActionPerformed
        new Thread(){
            @Override
            public void run(){
                while(true){
                    try {
                        //String mau = cl.getColor1();
                        txtJava.setForeground(list.get(0));
                        Thread.sleep(500);
                         Collections.shuffle(list);
                       // break;
                    } catch (InterruptedException ex) {
                    }
                }
            }
        }.start();
        //txtJava.setForeground(;
    }//GEN-LAST:event_btnJavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Color2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJava;
    private javax.swing.JLabel txtJava;
    // End of variables declaration//GEN-END:variables
}
