/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buoi6;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JLabel;

/**
 *
 * @author Tinh
 */
public class demo2 extends javax.swing.JFrame {

    /**
     * Creates new form demo2
     */
    public demo2() {
        initComponents();
        Hashtable data= new Hashtable();
        String [] sMonths = {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
        for(int i = 0; i<12; i++){
            data.put(i, new JLabel(sMonths[i]));
        }
        ldthang.setLabelTable(data);
        
        Calendar can = Calendar.getInstance();
        ldngay.setValue(can.get(Calendar.DAY_OF_MONTH));
        ldthang.setValue(can.get(Calendar.MONTH));
        ldnam.setValue(can.get(Calendar.YEAR));
        displayDate();
    }
    
    void displayDate(){
        SimpleDateFormat sdf = new SimpleDateFormat("EEE, dd - MMM - yyyy");
        int dd = ldngay.getValue();
        int mm = ldthang.getValue();
        int yy = ldnam.getValue() - 1900;
        Date d = new Date(yy, mm, dd);
        txtngay.setText(sdf.format(d));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ldngay = new javax.swing.JSlider();
        ldthang = new javax.swing.JSlider();
        ldnam = new javax.swing.JSlider();
        txtngay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ldngay.setMajorTickSpacing(3);
        ldngay.setMaximum(31);
        ldngay.setMinimum(1);
        ldngay.setMinorTickSpacing(1);
        ldngay.setPaintLabels(true);
        ldngay.setPaintTicks(true);
        ldngay.setSnapToTicks(true);
        ldngay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ldngayStateChanged(evt);
            }
        });

        ldthang.setMajorTickSpacing(1);
        ldthang.setMaximum(11);
        ldthang.setMinorTickSpacing(1);
        ldthang.setPaintLabels(true);
        ldthang.setPaintTicks(true);
        ldthang.setSnapToTicks(true);
        ldthang.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ldthangStateChanged(evt);
            }
        });

        ldnam.setMajorTickSpacing(5);
        ldnam.setMaximum(2030);
        ldnam.setMinimum(2000);
        ldnam.setMinorTickSpacing(1);
        ldnam.setPaintLabels(true);
        ldnam.setPaintTicks(true);
        ldnam.setSnapToTicks(true);
        ldnam.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ldnamStateChanged(evt);
            }
        });

        txtngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ldnam, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(ldthang, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(ldngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtngay))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(ldngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(ldthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(ldnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(txtngay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngayActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtngayActionPerformed

    private void ldngayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ldngayStateChanged
        // TODO add your handling code here:
        displayDate();
        
    }//GEN-LAST:event_ldngayStateChanged

    private void ldthangStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ldthangStateChanged
        // TODO add your handling code here:
        displayDate();
    }//GEN-LAST:event_ldthangStateChanged

    private void ldnamStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ldnamStateChanged
        // TODO add your handling code here:
        displayDate();
    }//GEN-LAST:event_ldnamStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider ldnam;
    private javax.swing.JSlider ldngay;
    private javax.swing.JSlider ldthang;
    private javax.swing.JTextField txtngay;
    // End of variables declaration//GEN-END:variables
}
