/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.NhanVien;
import Model.User;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class JFrameMenu extends javax.swing.JFrame {

    int index = -1;

    /**
     * Creates new form Menu
     */
    public JFrameMenu() {
        if (User.isLogin()) {
            initComponents();
            init();
            Utility.UtilityImage.setIconTitle(this, "Icon-title.png");
            setTitle("Trang chủ");
            if (!User.isTruongPhong()) {
                pnlMenu.remove(pnlThonKe);
                pnlMenu.remove(pnlNhanVien);
            }
        } else {
            this.dispose();
            new JFrameDangnhap().setVisible(true);
        }
    }

  

    public void init() {
        pnlMain.add(pnlTop, BorderLayout.PAGE_START);
        index = 1;
        addJPanelBody(new TrangChu());
        pnlTrangChu.setBackground(Color.white);
        lbltrangchu.setForeground(new Color(175, 175, 220));
        pack();
        setLocationRelativeTo(null);
    }

    public void addJPanelBody(JPanel pnl) {
        if (pnlMain.getComponentCount() > 1) {
            pnlMain.remove(1); //xóa jpanel đã tồn tại trước đó       
        }
        int width = 1100;      //reset kích thước mặc định
        int height = 155;
        int NewWidth = (int) pnl.getPreferredSize().getWidth();
        int NewHeight = (int) pnl.getPreferredSize().getHeight(); //lấy kích thước jpanel mới 
        if (NewWidth > width) {
            width += NewWidth - width;  //neu jpanel moi co kich thuong lon hon mac dich sẽ cộng phần lớn hơn đó vào
        }
        if (NewHeight > height) {
            height += NewHeight; //neu jpanel moi co kich thuong lon hon mac dich sẽ cộng phần lớn hơn đó vào
        }
        pnlMain.add(pnl, BorderLayout.CENTER);
        pnlMain.setPreferredSize(new Dimension(width, height));
        this.revalidate();
        this.repaint();             //yeu cầu vẽ lại jframe

    }

    public void RemoveSelected() {
        if (index > -1) {
            JPanel pnl = (JPanel) pnlMenu.getComponents()[index];
            pnl.setBackground(new Color(175, 175, 220));
            JLabel lbl = (JLabel) pnl.getComponent(0);
            lbl.setForeground(Color.white);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel()
        ;
        pnlMenu = new javax.swing.JPanel()
        ;
        pnlThoat = new javax.swing.JPanel();
        lbldangxuat = new javax.swing.JLabel();
        pnlTrangChu = new javax.swing.JPanel();
        lbltrangchu = new javax.swing.JLabel();
        pnlThonKe = new javax.swing.JPanel();
        lblthongke = new javax.swing.JLabel();
        pnlGioHang = new javax.swing.JPanel();
        lblgiohang = new javax.swing.JLabel();
        pnlHoaDon = new javax.swing.JPanel();
        lblHoadon = new javax.swing.JLabel();
        pnlXeMay = new javax.swing.JPanel();
        lblXemay = new javax.swing.JLabel();
        pnlPhuKien = new javax.swing.JPanel();
        lblphukien = new javax.swing.JLabel();
        pnlNhanVien = new javax.swing.JPanel();
        lblNhanvien = new javax.swing.JLabel();
        pnlKhachhang = new javax.swing.JPanel();
        lblKhachhang = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        pnlTop.setBackground(new java.awt.Color(175, 175, 220));
        pnlTop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        pnlTop.setMinimumSize(new java.awt.Dimension(900, 0));
        pnlTop.setPreferredSize(new java.awt.Dimension(1066, 105));

        pnlMenu.setBackground(new java.awt.Color(106, 106, 180));

        pnlThoat.setBackground(new java.awt.Color(175, 175, 220));

        lbldangxuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbldangxuat.setForeground(new java.awt.Color(255, 255, 255));
        lbldangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-exit-44.png"))); // NOI18N
        lbldangxuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbldangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangxuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlThoatLayout = new javax.swing.GroupLayout(pnlThoat);
        pnlThoat.setLayout(pnlThoatLayout);
        pnlThoatLayout.setHorizontalGroup(
            pnlThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
            .addGroup(pnlThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlThoatLayout.createSequentialGroup()
                    .addComponent(lbldangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlThoatLayout.setVerticalGroup(
            pnlThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbldangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        pnlTrangChu.setBackground(new java.awt.Color(175, 175, 220));

        lbltrangchu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltrangchu.setForeground(new java.awt.Color(255, 255, 255));
        lbltrangchu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-home-36.png"))); // NOI18N
        lbltrangchu.setText("Trang chủ");
        lbltrangchu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbltrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbltrangchuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTrangChuLayout = new javax.swing.GroupLayout(pnlTrangChu);
        pnlTrangChu.setLayout(pnlTrangChuLayout);
        pnlTrangChuLayout.setHorizontalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
            .addGroup(pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbltrangchu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
        );
        pnlTrangChuLayout.setVerticalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbltrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        pnlThonKe.setBackground(new java.awt.Color(175, 175, 220));

        lblthongke.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblthongke.setForeground(new java.awt.Color(255, 255, 255));
        lblthongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-chart-36.png"))); // NOI18N
        lblthongke.setText("Thống kê");
        lblthongke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthongkeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlThonKeLayout = new javax.swing.GroupLayout(pnlThonKe);
        pnlThonKe.setLayout(pnlThonKeLayout);
        pnlThonKeLayout.setHorizontalGroup(
            pnlThonKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblthongke, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );
        pnlThonKeLayout.setVerticalGroup(
            pnlThonKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlGioHang.setBackground(new java.awt.Color(175, 175, 220));

        lblgiohang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-cart-44.png"))); // NOI18N
        lblgiohang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblgiohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblgiohangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlGioHangLayout = new javax.swing.GroupLayout(pnlGioHang);
        pnlGioHang.setLayout(pnlGioHangLayout);
        pnlGioHangLayout.setHorizontalGroup(
            pnlGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblgiohang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlGioHangLayout.setVerticalGroup(
            pnlGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblgiohang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlHoaDon.setBackground(new java.awt.Color(175, 175, 220));

        lblHoadon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHoadon.setForeground(new java.awt.Color(255, 255, 255));
        lblHoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-bill-36.png"))); // NOI18N
        lblHoadon.setText("Hóa đơn");
        lblHoadon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoadonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHoadon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addComponent(lblHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlXeMay.setBackground(new java.awt.Color(175, 175, 220));

        lblXemay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblXemay.setForeground(new java.awt.Color(255, 255, 255));
        lblXemay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXemay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-moto-36.png"))); // NOI18N
        lblXemay.setText("Xe máy");
        lblXemay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblXemay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXemayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlXeMayLayout = new javax.swing.GroupLayout(pnlXeMay);
        pnlXeMay.setLayout(pnlXeMayLayout);
        pnlXeMayLayout.setHorizontalGroup(
            pnlXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlXeMayLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblXemay, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlXeMayLayout.setVerticalGroup(
            pnlXeMayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblXemay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlPhuKien.setBackground(new java.awt.Color(175, 175, 220));

        lblphukien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblphukien.setForeground(new java.awt.Color(255, 255, 255));
        lblphukien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphukien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-wrench-36.png"))); // NOI18N
        lblphukien.setText("Phụ kiện");
        lblphukien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblphukien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblphukienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlPhuKienLayout = new javax.swing.GroupLayout(pnlPhuKien);
        pnlPhuKien.setLayout(pnlPhuKienLayout);
        pnlPhuKienLayout.setHorizontalGroup(
            pnlPhuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhuKienLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblphukien, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPhuKienLayout.setVerticalGroup(
            pnlPhuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblphukien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlNhanVien.setBackground(new java.awt.Color(175, 175, 220));

        lblNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNhanvien.setForeground(new java.awt.Color(255, 255, 255));
        lblNhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-employee-30.png"))); // NOI18N
        lblNhanvien.setText("Nhân viên");
        lblNhanvien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanvienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlKhachhang.setBackground(new java.awt.Color(175, 175, 220));

        lblKhachhang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKhachhang.setForeground(new java.awt.Color(255, 255, 255));
        lblKhachhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-customer-30.png"))); // NOI18N
        lblKhachhang.setText("Khách hàng");
        lblKhachhang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhachhangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlKhachhangLayout = new javax.swing.GroupLayout(pnlKhachhang);
        pnlKhachhang.setLayout(pnlKhachhangLayout);
        pnlKhachhangLayout.setHorizontalGroup(
            pnlKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlKhachhangLayout.setVerticalGroup(
            pnlKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlThonKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(pnlGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlXeMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPhuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlGioHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTrangChu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlKhachhang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPhuKien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlXeMay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThonKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbldangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuatMouseClicked
        new LoadingJFrame(new JFrameDangnhap());
        this.dispose();
        User.Logout();
    }//GEN-LAST:event_lbldangxuatMouseClicked

    private void lblphukienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblphukienMouseClicked
        RemoveSelected();
        index = 6;
        if (!User.isTruongPhong()) {
            index--;
        }
        addJPanelBody(new QuanLyPhuKien());
        pnlPhuKien.setBackground(Color.white);
        lblphukien.setForeground(new Color(175, 175, 220));
    }//GEN-LAST:event_lblphukienMouseClicked

    private void lblXemayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXemayMouseClicked
        RemoveSelected();
        index = 5;
        if (!User.isTruongPhong()) {
            index--;
        }
        addJPanelBody(new QuanLyXeMay());
        pnlXeMay.setBackground(Color.white);
        lblXemay.setForeground(new Color(175, 175, 220));
    }//GEN-LAST:event_lblXemayMouseClicked

    private void lbltrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltrangchuMouseClicked
        RemoveSelected();
        index = 1;
        addJPanelBody(new TrangChu());

        pnlTrangChu.setBackground(Color.white);
        lbltrangchu.setForeground(new Color(175, 175, 220));
    }//GEN-LAST:event_lbltrangchuMouseClicked

    private void lblHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoadonMouseClicked
        RemoveSelected();
        index = 4;
        if (!User.isTruongPhong()) {
            index--;
        }
        addJPanelBody(new QuanLyHoaDon());

        pnlHoaDon.setBackground(Color.white);
        lblHoadon.setForeground(new Color(175, 175, 220));
    }//GEN-LAST:event_lblHoadonMouseClicked

    private void lblNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanvienMouseClicked
        RemoveSelected();
        index = 7;
        addJPanelBody(new QuanLyNhanVien());

        pnlNhanVien.setBackground(Color.white);
        lblNhanvien.setForeground(new Color(175, 175, 220));
    }//GEN-LAST:event_lblNhanvienMouseClicked

    private void lblKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachhangMouseClicked
        RemoveSelected();
        index = 8;
        if (!User.isTruongPhong()) {
            index -= 2;
        }
        addJPanelBody(new QuanLyKhachHang());

        pnlKhachhang.setBackground(Color.white);
        lblKhachhang.setForeground(new Color(175, 175, 220));
    }//GEN-LAST:event_lblKhachhangMouseClicked

    private void lblgiohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblgiohangMouseClicked
        RemoveSelected();
        index = 3;
        if (!User.isTruongPhong()) {
            index--;
        }
        addJPanelBody(new QuanLyGiohang());
        pnlGioHang.setBackground(Color.white);
        lblgiohang.setForeground(new Color(175, 175, 220));
    }//GEN-LAST:event_lblgiohangMouseClicked

    private void lblthongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthongkeMouseClicked
        RemoveSelected();
        index = 2;
        addJPanelBody(new ThongKe());

        pnlThonKe.setBackground(Color.white);
        lblthongke.setForeground(new Color(175, 175, 220));
    }//GEN-LAST:event_lblthongkeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHoadon;
    private javax.swing.JLabel lblKhachhang;
    private javax.swing.JLabel lblNhanvien;
    private javax.swing.JLabel lblXemay;
    private javax.swing.JLabel lbldangxuat;
    private javax.swing.JLabel lblgiohang;
    private javax.swing.JLabel lblphukien;
    private javax.swing.JLabel lblthongke;
    private javax.swing.JLabel lbltrangchu;
    private javax.swing.JPanel pnlGioHang;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlKhachhang;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlPhuKien;
    private javax.swing.JPanel pnlThoat;
    private javax.swing.JPanel pnlThonKe;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlTrangChu;
    private javax.swing.JPanel pnlXeMay;
    // End of variables declaration//GEN-END:variables
}
