/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.ThongKeDAO;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.event.MouseInputListener;
import Utility.UtilityDate;
import Utility.UtilityImage;
import Model.User;
import ViewThongke.DoanhthuNhanvien;
import ViewThongke.ThongkeKhachmoi;
import ViewThongke.ThongkeTongthu;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Calendar;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
* @author ADMIN
 */
public class ThongKe extends javax.swing.JPanel {
    /**
     * Creates new form NewJPanel
     */
    public ThongKe() {
        initComponents();
        
    }
    public void addJPanel(JPanel pnl){
        pnlCenter.removeAll();
        pnlCenter.add(pnl,BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgVaitro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnThongke1 = new javax.swing.JButton();
        btnThongke2 = new javax.swing.JButton();
        btnThongke3 = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(940, 510));

        jPanel1.setBackground(new java.awt.Color(171, 171, 215));

        btnThongke1.setText("Thống kê tổng thu");
        btnThongke1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongke1ActionPerformed(evt);
            }
        });

        btnThongke2.setText("Thống kê doanh thu nhân viên");
        btnThongke2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongke2ActionPerformed(evt);
            }
        });

        btnThongke3.setText("Thống kê khách hàng mới");
        btnThongke3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongke3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThongke2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongke1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongke3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThongke1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThongke2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThongke3)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        pnlCenter.setBackground(new java.awt.Color(250, 241, 241));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongke1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongke1ActionPerformed
        addJPanel(new ThongkeTongthu());
    }//GEN-LAST:event_btnThongke1ActionPerformed

    private void btnThongke2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongke2ActionPerformed
        addJPanel(new DoanhthuNhanvien());
    }//GEN-LAST:event_btnThongke2ActionPerformed

    private void btnThongke3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongke3ActionPerformed
         addJPanel(new ThongkeKhachmoi());
    }//GEN-LAST:event_btnThongke3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgVaitro;
    private javax.swing.JButton btnThongke1;
    private javax.swing.JButton btnThongke2;
    private javax.swing.JButton btnThongke3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlCenter;
    // End of variables declaration//GEN-END:variables
}
