/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.User;
import Utility.UtilityImage;
import java.awt.Desktop;
import java.awt.FlowLayout;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class TrangChu extends javax.swing.JPanel {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        jPanel1.setLayout(new FlowLayout(FlowLayout.CENTER)); // Cài đặt LayoutManager để đặt JLabel giữa JPanel
        lblhinh.setIcon(UtilityImage.ResizeHinhTheoPreferrsize(lblhinh, "src//Icon//background3.png"));
        jPanel1.add(lblhinh);
        clock();
    }

    private void clock() {
        Runnable r1 = () -> {
            SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");

            while (true) {
                Date date = new Date();
                lblThoigian1.setText(formatter.format(date));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }

        };
        new Thread(r1).start();

    }

    void openWebsite() {
        try {
            File htmlFile = new File("src//Huongdan//Baove1.html");
            Desktop.getDesktop().browse(htmlFile.toURI());

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "không tìm thấy file hướng dẫn");
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblhinh = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblHuongdan = new javax.swing.JLabel();
        lblThoigian1 = new javax.swing.JLabel();

        lblhinh.setMaximumSize(new java.awt.Dimension(812, 319));
        lblhinh.setMinimumSize(new java.awt.Dimension(812, 319));
        lblhinh.setPreferredSize(new java.awt.Dimension(812, 319));

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(940, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(175, 175, 220));

        lblHuongdan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHuongdan.setForeground(new java.awt.Color(255, 255, 255));
        lblHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-question-mark-40.png"))); // NOI18N
        lblHuongdan.setText("Hướng dẫn");
        lblHuongdan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHuongdan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblHuongdanAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblHuongdan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHuongdanMouseClicked(evt);
            }
        });

        lblThoigian1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblThoigian1.setForeground(new java.awt.Color(255, 255, 255));
        lblThoigian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-clock-40.png"))); // NOI18N
        lblThoigian1.setText("lbl thoi gian");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHuongdan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThoigian1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHuongdan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblThoigian1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblHuongdanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblHuongdanAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHuongdanAncestorAdded

    private void lblHuongdanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuongdanMouseClicked
        // TODO add your handling code here:
        openWebsite();
    }//GEN-LAST:event_lblHuongdanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHuongdan;
    private javax.swing.JLabel lblThoigian1;
    private javax.swing.JLabel lblhinh;
    // End of variables declaration//GEN-END:variables
}
